kytos/cli/commands/napps/api.py, kytos/utils/napps/manager.py
=> Napps uninstall

bin/kytos, kytos_utils/cli/cmdline.py
=> Enable commands not using docopts

setup.py
=> Changing setup.py develop to install sym link

kytos/cli/commands/napps/api.py, kytos/cli/commands/napps/parser.py, kytos/utils/client.py, kytos/utils/napps.py
=> Napps search

kytos/utils/napps.py
=> Fix remote and local install conflict

kytos/utils/napps.py
=> Fixing typo

AUTHORS.rst, LICENSE, README.md, README.rst
- Improving README.rst
- Adding AUTHORS.rst
- Adding LICENSE file with license MIT
=> Improving repository

README.rst
=> Fix python version in readme

bin/kytos, kytos/cli/commands/napps/parser.py, kytos/cli/commands/users/__init__.py, kytos/cli/commands/users/api.py, kytos/cli/commands/users/parser.py, kytos/utils/client.py, kytos/utils/users.py
=> Adding users creation in command line

kytos/cli/commands/napps/api.py, kytos/cli/commands/napps/parser.py
Add command to disable all napps installed and enabled
Add command to enable all napps installed and disabled
=> Add commands 'kytos napps (enable/disable) all'

kytos/cli/commands/napps/api.py, kytos/utils/client.py, kytos/utils/napps.py
=> Adding install NApps dependecies

CHANGELOG.rst, kytos/cli/commands/napps/api.py, kytos/cli/commands/napps/parser.py, kytos/cli/commands/users/parser.py, kytos/utils/client.py, kytos/utils/config.py, kytos/utils/decorators.py, kytos/utils/napps.py, setup.py
kytos commands will request the configuration loaded by kytos instance
before install and enable napps.
Fix kytos/kytos-utils#85
=> Change to use napps_dir from kytos instance

etc/skel/kytos/napp-structure/username/napp/main.py.template
Import `KytosNApp` and `log` from correct place
=> Fix SKEL file to match changes in Kytos

kytos/cli/commands/napps/api.py
- When enabling a NApp, all NApp dependencies will be enabled too.
=> Improving enable napp

etc/skel/kytos/napp-structure/username/napp/kytos.json.template, kytos/utils/napps.py
=> Fix NApp version

kytos/utils/napps.py
=> Update kytos/config API URL

kytos/utils/napps.py
=> Ignore openapi template when creating a NApp

kytos/cli/commands/napps/api.py
=> Show warning when a NApp is already installed

CHANGELOG.rst
=> [CHANGELOG] Update realease to 2017.2b2

kytos/cli/commands/web/api.py, kytos/cli/commands/web/parser.py
- Now the command 'kytos web update' receive a version as parameter
=> Add version in kytos web update command

CHANGELOG.rst, kytos/cli/commands/napps/api.py, kytos/cli/commands/napps/parser.py, kytos/utils/napps.py
=> Added flag --meta to create meta-package

kytos/cli/commands/napps/api.py
Fixes #193 
A few manual tests:
```
❯ kytos napps install foo/bar
INFO    NApp foo/bar:
INFO      Searching local NApp...
INFO      Not found. Downloading from NApps Server...
ERROR     NApp not found.
~/repos/kytos master* ⇡
❯ kytos napps install kytos/of_lldp
INFO    NApp kytos/of_lldp:
WARNING   Napp already enabled.
❯ kytos napps install kytos/flow_manager
INFO    NApp kytos/flow_manager:
INFO      Searching local NApp...
INFO      Not found. Downloading from NApps Server...
INFO      Downloaded and installed.
INFO      Enabling...
INFO      Enabled.
INFO  Installing Dependencies:
INFO    NApp kytos/of_core:
WARNING   Napp already enabled.
```
=> Enhanced error handling when installing invalid NApps. #193

kytos/cli/commands/web/api.py, kytos/utils/client.py, kytos/utils/napps.py, requirements/dev.txt
Updated requirements to match Kytos 2018.2 dependencies' versions.
Also fixed many linter issues required by the new pylint.
=> Requirements update to match Kytos Core 2018.2

kytos/utils/napps.py, kytos/utils/settings.py, setup.py
Also added better handling of corner cases (like an empty skel dir).
=> Fix NApp creation from skel dir (fix #190)

kytos/utils/napps.py
NApps upload does not package .tox and .git now.
=> Fix packaging in upload NApps (#209).

kytos/utils/napps.py
Added comments on regex statements and changed way to ignore files.
=> Changed regex statements

kytos/utils/napps.py
Solving issue related to Napp Packing
=> Fix NApp packaging

kytos/cli/commands/napps/api.py, kytos/utils/napps.py
Now, this action is done by kytos core
=> Remove NApps installation (Fix #245)

kytos/utils/napps.py, requirements/dev.in, requirements/dev.txt, requirements/run.in, requirements/run.txt
Kytos was uploading some files present in .gitgnore. This commit includes a lib to parse .gitignore, ignoring all files present in this file.
=> Change .gitignore parser (Fix #221)

kytos/utils/napps.py, setup.py
There were some linter issues raised by new Pylint version. This commit fixes all of them.
=> Fix new linter issues

setup.py
Travis result is positive even when some unit tests fail in the Coverage process. This PR fix it.
Fix issue #285
=> Fix Travis false positive message

README.rst
Solve the problem of broken links to the contribution guide.
=> Update link to how to contribute on README.rst

kytos/templates/skel/napp-structure/username/napp/main.py.template
Update NApp (main.py) template to use "NApp" instead of "napp".
- Update NApp template
=> Update NApp template

Makefile, README.rst, setup.py
Related https://github.com/kytos/kytos/issues/1149
Remove python3.6 references
=> Remove python3.6 references

CHANGELOG.rst, bin/kytos, kytos/cli/commands/bug_report/__init__.py, kytos/cli/commands/bug_report/api.py, kytos/cli/commands/bug_report/parser.py, setup.py
=> Add bug-report command line

kytos/utils/decorators.py, tests/unit/test_decorators.py
Adjust @slinksoft @niehaus PR.
Fix #311
=> Prompt user to reenter credentials when create napps upload fails

kytos/utils/napps.py
Adjust @slinksoft @Niehaus  PR.
Fix #310
=> Friendly response to Keyboard Interrupt in the NApp creation

setup.py
Require `pytest-runner` only when testing
- N/A
=> Require pytest-runner only when testing
